---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: this is meta description
- type: image_gallery
  name: images
  label: post image(s)
  description: Project image(s); the 1st image is visible, the others are only used for Open Graph metadata
- type: file
  name: bg_image
  label: background image
  description: Page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
